apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talensavvy-dev-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.org/ssl-services: "eclwatch"
spec:
  tls:
  - hosts:
    - "talentsavvy.com"
    secretName: talentsavvy-dev-tls
  rules:
  - http:
      paths:
      - path: /backend(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: talentsavvy-be
            port:
              number: 8080
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: talentsavvy-fe
            port:
              number: 443
